### ISSUE TITLE
Skeleton Layer page is empty

### ISSUE THREAD

**Issue by rodolforg** [synfig/synfig-docs#23]
Although we have description here: https://github.com/synfig/synfig-docs/blob/master/source/layers/skeleton.rst
The related page is empty: https://synfig.readthedocs.io/en/latest/layers/skeleton.html

**Comment by morevnaproject** [comment]
Hi! It should show correctly now. Can you please check? ^__^

**Comment by rodolforg** [comment]
Now we have contents! Thanks! :)

But links in this page are broken :(

**Comment by morevnaproject** [comment]
> But links in this page are broken :(

Yes, at the moment all converted pages have broken links - we will fix links in 2nd pass (when we have all pages moved from old wiki). More info about this [here](https://forums.synfig.org/t/new-documentation/10931/12?u=konstantindmitriev). ^__^
