### ISSUE TITLE
Release notes currently at https://synfig.readthedocs.io/en/latest/main_concepts/interface.html

### ISSUE THREAD

**Issue by asdf23** [synfig/synfig-docs#26]
The 3rd image and description below do not seem to match, or I'm not able to find what the text is describing.

**Comment by morevnaproject** [comment]
Hi! Do you mean this part? -
![screenshot_001](https://user-images.githubusercontent.com/332868/117143460-12377700-addb-11eb-876d-e331431f3ce9.png)

**Comment by morevnaproject** [comment]
Closed because of no response from OP.
